### ISSUE TITLE
Crop around signature

### ISSUE THREAD

**Issue by arr00** [ipraba/EPSignature#10]
Is there any way to crop the UIImage around the signature? Right now I end up with a large UIImage that is mostly empty. Thanks

**Comment by ipraba** [comment]
@arr00 boundingRect value of this delegate below will return you the bounding rect of the signature drawn.
`func epSignature(_: EPSignature.EPSignatureViewController, didSigned signatureImage: UIImage, boundingRect: CGRect)`

**Comment by arr00** [comment]
Oh wow, can't believe I missed that. Thanks so much! Also, thanks for this repo, it is very useful for an app that I am currently developing.

Just in case anyone wondering though here is wondering what the actual code to crop the image is, I'll post it bellow.

`let imageRef = CGImageCreateWithImageInRect(signatureImage.CGImage, boundingRect)`
