### ISSUE TITLE
Swift 3.0 Support

### ISSUE THREAD

**Issue by Highstorm** [ipraba/EPSignature#18]
Hi there,

will there be a swift 3.0 branch of your code in the near future?

**Comment by arcioneo** [comment]
Have the same issue here, cannot use it in xcode 10

**Comment by ipraba** [comment]
I will update to swift3.0 very soon.

**Comment by ipraba** [comment]
Updated to swift3.0. Kindly update your pods to get the latest EPSignature(1.0.3). https://github.com/ipraba/EPSignature/releases/tag/1.0.3
👍🏽
