### ISSUE TITLE
Getting the signature strokes without the extra whitespace?

### ISSUE THREAD

**Issue by JinkProject** [ipraba/EPSignature#30]
Currently there is a method that returns the bounds of the signature without the extra whitespace from the signature view. That is great, but why, then, did you not implement a method that would return the signature without the extra whitespace?

**Comment by ipraba** [comment]
Because i thought to give options to the users. People who need the signature image without extra whitespace can crop the UIImage by passing the bounding rect.

If you are interested can check this for cropping UIImage http://stackoverflow.com/questions/158914/cropping-an-uiimage

thanks
