### ISSUE TITLE
Swift 4 Support

### ISSUE THREAD

**Issue by joaogithub** [ipraba/EPSignature#43]
I'm using EPSignature 1.0.3 as a dependency of my private Cocoa Pod.
I've got several other dependencies in my pod spec file, all supporting Swift 4.
I cannot get my pod spec through lint validation if I include EPSignature as a dependency. 

I'm getting the following errors when running `pod spec lint` command:
`  - ERROR | [iOS] xcodebuild:  EPSignature/Pod/Classes/EPSignatureViewController.swift:42:117: error: argument of '#selector' refers to instance method 'onTouchCancelButton()' that is not exposed to Objective-C
    - NOTE  | [iOS] xcodebuild:  EPSignature/Pod/Classes/EPSignatureViewController.swift:103:10: note: add '@objc' to expose this instance method to Objective-C
    - ERROR | [iOS] xcodebuild:  EPSignature/Pod/Classes/EPSignatureViewController.swift:46:113: error: argument of '#selector' refers to instance method 'onTouchDoneButton()' that is not exposed to Objective-C
    - NOTE  | [iOS] xcodebuild:  EPSignature/Pod/Classes/EPSignatureViewController.swift:108:10: note: add '@objc' to expose this instance method to Objective-C
    - ERROR | [iOS] xcodebuild:  EPSignature/Pod/Classes/EPSignatureViewController.swift:48:115: error: argument of '#selector' refers to instance method 'onTouchClearButton()' that is not exposed to Objective-C
    - NOTE  | [iOS] xcodebuild:  EPSignature/Pod/Classes/EPSignatureViewController.swift:144:10: note: add '@objc' to expose this instance method to Objective-C
    - ERROR | [iOS] xcodebuild:  EPSignature/Pod/Classes/EPSignatureViewController.swift:60:123: error: argument of '#selector' refers to instance method 'onTouchActionButton' that is not exposed to Objective-C`

These errors are related to Swift 3 to Swift 4 conversion. 
Is there any expected time for EPSignature to support Swift 4?

Thanks and congrats on your work

**Comment by priyankagaikwad** [comment]
Hi
I also need swift 4 support for this. Is there any update for this?

**Comment by ipraba** [comment]
Now the library is updated with swift4 in the version 1.0.6. Kindly update your pods. Apologies for late update. 😔
